cuppa-framework/cuppa

.travis.yml
README.md
checkstyle-rules.xml
checkstyle-test-suppressions.xml
pom.xml
src/main/java/org/forgerock/cuppa/Cuppa.java
src/main/java/org/forgerock/cuppa/CuppaException.java
src/main/java/org/forgerock/cuppa/DescribeBlock.java
src/main/java/org/forgerock/cuppa/Function.java
src/main/java/org/forgerock/cuppa/TestBlock.java
src/main/java/org/forgerock/cuppa/TestResults.java
src/main/java/org/forgerock/cuppa/package-info.java
src/test/java/org/forgerock/cuppa/CuppaTest.java

Adds the API for the basic test declaration:
```java
describe('Array', function() {
describe('#indexOf()', function () {
it('should return -1 when the value is not present', function () {
assert.equal(-1, [1,2,3].indexOf(5));
assert.equal(-1, [1,2,3].indexOf(0));
});
});
});
```
Also checkstyle has been introduced. Most of the available checkstyle rules have been enabled with the intention of evaluating each rule when rule violations occur to determine if the rule adds value or impedes development.

Add support for basic api

---

checkstyle-rules.xml
pom.xml
src/main/java/org/forgerock/cuppa/Cuppa.java
src/main/java/org/forgerock/cuppa/DescribeBlock.java
src/test/java/org/forgerock/cuppa/CuppaTest.java

Adds support for before, after, beforeEach and afterEach.
```java
describe('hooks', function() {
before(function() {
// runs before all tests in this block
});
after(function() {
// runs after all tests in this block
});
beforeEach(function() {
// runs before each test in this block
});
afterEach(function() {
// runs after each test in this block
});
// test cases
});
```

Add support for before, after, beforeEach and afterEach

---

pom.xml

Since renaming the test classes to *Tests.java maven has not been running the tests. This changes configures the maven surefire plugin to run tests for the following patterns:
* ***/**Test.java
* ***/**Tests.java

Make tests run through maven

---

cuppa-core/src/test/java/org/forgerock/cuppa/HookTests.java

"warning: non-varargs call of varargs method with inexact argument
type for last parameter"

Fix java build warning

---

README.md
config/checkstyle/checkstyle.xml
cuppa-surefire/src/main/java/org/forgerock/cuppa/maven/surefire/CuppaSurefireProvider.java
cuppa/src/main/java/org/forgerock/cuppa/Cuppa.java
cuppa/src/main/java/org/forgerock/cuppa/CuppaTestProvider.java
cuppa/src/main/java/org/forgerock/cuppa/internal/InternalTestBlockBuilder.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestBuilderImpl.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestContainer.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestRunner.java
cuppa/src/main/java/org/forgerock/cuppa/model/Behaviour.java
cuppa/src/main/java/org/forgerock/cuppa/model/Tags.java
cuppa/src/main/java/org/forgerock/cuppa/model/Test.java
cuppa/src/main/java/org/forgerock/cuppa/model/TestBlock.java
cuppa/src/main/java/org/forgerock/cuppa/model/TestBlockBuilder.java
cuppa/src/main/java/org/forgerock/cuppa/model/TestBuilder.java
cuppa/src/test/java/org/forgerock/cuppa/TaggedTests.java
docs/_config.yml
docs/_data/docs.yml
docs/_docs/skipping-tests.md
docs/_docs/tagging-tests.md

Adds support for tests to be tagged and integrates with surefire to handle groups specified via TestNG "groups/excludedGroups" if TestNG is on the classpath otherwise provides "tag/excludedTags" surefire property via the pom.xml or can be overridden using -Dtag=group on the command line.
No integration with JUnit as of yet as unsure on how JUnit deals with groups.

Add support for tagging tests

---

cuppa-junit/src/main/java/org/forgerock/cuppa/junit/CuppaRunner.java
cuppa-junit/src/main/java/org/forgerock/cuppa/junit/ReportJUnitAdapter.java
cuppa-junit/src/test/java/org/forgerock/cuppa/junit/CuppaRunnerTest.java

The JUnit `Description` class provides an overloaded constructor that allows you to specify a unique id. I've used the full string description of the block/test. Would be nice to just be able to pass the `TestBlock`/`Test` itself, but unfortunately right now they do not use their parents to compare themselves, so it wouldn't fix the problem.
Fixes #60.

Ensure JUnit descriptions are unique

---

config/checkstyle/checkstyle.xml
cuppa-junit/src/main/java/org/forgerock/cuppa/junit/ReportJUnitAdapter.java
cuppa-surefire/src/main/java/org/forgerock/cuppa/maven/surefire/CuppaSurefireReporter.java
cuppa/src/main/java/org/forgerock/cuppa/Runner.java
cuppa/src/main/java/org/forgerock/cuppa/internal/EmptyTestBlockFilter.java
cuppa/src/main/java/org/forgerock/cuppa/internal/OnlyTestBlockFilter.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TagTestBlockFilter.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestBlockBuilder.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestContainer.java
cuppa/src/main/java/org/forgerock/cuppa/model/Hook.java
cuppa/src/main/java/org/forgerock/cuppa/model/HookType.java
cuppa/src/main/java/org/forgerock/cuppa/model/TestBlock.java
cuppa/src/main/java/org/forgerock/cuppa/reporters/DefaultReporter.java
cuppa/src/test/java/org/forgerock/cuppa/ModelFinder.java
cuppa/src/test/java/org/forgerock/cuppa/reporters/DefaultReporterTest.java

We weren't really reporting hook errors, but they're actually very common so it's important we do.
The second commit is an optional refactor that I'd like to get your thoughts on. The motivation was to reduce the number of parameters on the `TestBlock` constructor, making it easier to write block transforms.

Improve reporting for hook errors

---

cuppa/src/main/java/org/forgerock/cuppa/Runner.java
cuppa/src/test/java/org/forgerock/cuppa/HookExceptionTests.java

Tests and/or hooks may choose to throw things like AssertionError. Cuppa should never allow these exceptions to halt test execution.

Catch Throwable instead of Exception

---

cuppa-junit/src/main/java/org/forgerock/cuppa/junit/ReportJUnitAdapter.java
cuppa-surefire/src/main/java/org/forgerock/cuppa/maven/surefire/CuppaSurefireReporter.java
cuppa/src/main/java/org/forgerock/cuppa/Runner.java
cuppa/src/main/java/org/forgerock/cuppa/reporters/DefaultReporter.java
cuppa/src/main/java/org/forgerock/cuppa/reporters/Reporter.java
cuppa/src/test/java/org/forgerock/cuppa/BasicApiTests.java
cuppa/src/test/java/org/forgerock/cuppa/HookExceptionTests.java
cuppa/src/test/java/org/forgerock/cuppa/ReportingTests.java

We introduced the distinction between fail and error in an attempt to be consistent with other Java test frameworks. Since JUnit 4 no longer makes this distinction, and the distinction is not common in other RSpec-style frameworks, we now feel that the it is unnecessary. Removing it simplifies Cuppa.
Fixes #63

Remove test error state

---

cuppa/src/main/java/org/forgerock/cuppa/CuppaException.java
cuppa/src/main/java/org/forgerock/cuppa/Runner.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestContainer.java
cuppa/src/test/java/org/forgerock/cuppa/BasicApiTests.java
cuppa/src/test/java/org/forgerock/cuppa/HookExceptionTests.java

This change improves the test coverage of the exceptions thrown by Cuppa and fixes several bugs uncovered by the improvements.

Improve Cuppa's use of exceptions

---

cuppa/src/main/java/org/forgerock/cuppa/model/Option.java
cuppa/src/main/java/org/forgerock/cuppa/model/Options.java
cuppa/src/main/java/org/forgerock/cuppa/model/TagsOption.java
cuppa/src/test/java/org/forgerock/cuppa/ModelTests.java

This allows Options to handle multiple Option of the same type.
Fixes #103

Add merge to the Option class

---

cuppa/src/main/java/org/forgerock/cuppa/Configuration.java
cuppa/src/main/java/org/forgerock/cuppa/Runner.java

This allows users to specify a reporter when they cannot control how Cuppa is run, for example if they are using Surefire.

Allow configuration provider to set an additional reporter

---

cuppa/src/main/java/org/forgerock/cuppa/internal/TestBlockRunner.java
cuppa/src/main/java/org/forgerock/cuppa/reporters/Reporter.java
cuppa/src/test/java/org/forgerock/cuppa/ExecutionTests.java

Hook start and pass events have been absent so far because I couldn't think of a reason why a reporter would want to receive them. However, they are useful if a reporter wants to time hooks, for example. Indeed, we should provide them so that a reporter can get a full picture of the execution.

Add reporter methods for hook start and pass

---

cuppa/src/main/java/org/forgerock/cuppa/Cuppa.java
cuppa/src/main/java/org/forgerock/cuppa/TestBuilder.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestBuilderImpl.java
cuppa/src/main/java/org/forgerock/cuppa/internal/TestContainer.java

This API design makes it difficult to call with() or tags() dynamically. I don't think there is much of a risk that users will use these APIs incorrectly.

Remove requirement to pass at least one Option or Tag to Cuppa methods

---

cuppa/src/main/java/org/forgerock/cuppa/Runner.java

Currently if Cuppa fails to instantiate a test class it does not log the name of that class, only the fact that it failed to instantiate a test class. Logging the name of the test class would add in debugging issues.

Log class name of class if failed to be instantiated

---

cuppa/src/main/java/org/forgerock/cuppa/internal/TestBuilderImpl.java
cuppa/src/main/java/org/forgerock/cuppa/model/Options.java
cuppa/src/main/java/org/forgerock/cuppa/model/Test.java
cuppa/src/main/java/org/forgerock/cuppa/model/TestBlock.java
cuppa/src/test/java/org/forgerock/cuppa/ModelTests.java
cuppa/src/test/java/org/forgerock/cuppa/OptionsTest.java

We offer the ability to manipulate `Options` by adding new `Option`s to it but offer no ability to remove `Option`s from it. This change will allow this without modifying the `Options` by returning a copy of it with the specified `Option` removed.
When adding new `Option`s I noticed we modify the same `Options` instance, should that be an immutable operation?

Allow remove of Option from Options

---

docs/_docs/junit-integration.md

A simple update to the documentation for the JUnit integration to include the Maven dependency for easy cut and pasting.

Update JUnit documentation to include Maven dependency

---

cuppa-surefire/src/main/java/org/forgerock/cuppa/maven/surefire/CuppaSurefireProvider.java
cuppa/src/main/java/org/forgerock/cuppa/Runner.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/AndCondition.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/Condition.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/ConditionFactory.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/ConditionWrapper.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/ContainsCondition.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/ExpressionParser.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/ExpressionTagTestBlockFilter.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/NotCondition.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/OrCondition.java
cuppa/src/main/java/org/forgerock/cuppa/internal/filters/expression/package-info.java
cuppa/src/main/java/org/forgerock/cuppa/internal/package-info.java
cuppa/src/main/java/org/forgerock/cuppa/model/Tags.java
cuppa/src/test/java/org/forgerock/cuppa/TaggedTests.java
cuppa/src/test/java/org/forgerock/cuppa/internal/filters/expression/ExpressionTagTestBlockFilterTest.java
docs/_docs/tagging-tests.md

This feature modifies the `TagTestBlockFilter` to handle the intersection groups. It also modifies the `ConfigurationProvider` to pass the plugin properties as a parameter.
That intersection group could have been added as a custom testTransforms from the configuration of my own project but it was a bit hacky because the current `TagTestBlockFilter` would have been applied to the test blocks after my own filter. Plus, in the transformer, it wasn't possible to get the properties defined in the surefire plugin.
I ended up creating that PR because I think other cuppa users could benefit it.
Example : 
`mvn verify -Dgroups=smoke -DintersectGroups=group1,group2`
Will return all the smoke tests plus the intersection of group1 and group2
Signed-off-by: Alex ROBUCHON <alex.robuchon@forgerock.com>

Add support for intersection groups

---

build.gradle
docs/_posts/2019-09-30-1.5.0-released.md

Fixes issue when trying to build and sign and updates version to 1.5.0

Fix duplicate key signature & Release Cuppa 1.5.0

---

build.gradle
cuppa-surefire/build.gradle

Updating the org.apache.maven.surefire 
surefire-api and common-java5 version to 2.22.2 for compatibility with AM's maven-surefire-plugin which has also been updated to 2.22.2 to support JUnit5 execution and reporting

Updating the org.apache.maven.surefire version to 2.22.2
